### ISSUE TITLE
I don't know why the speed is very slow

### ISSUE THREAD

**Issue by hotalex** [Nick088Official/FaceFusion-Online-Ports#1]

**Comment by Nick088Official** [comment]
Yea i just noticed that and fixed it, retry now, also be sure to use T4 free daily gpu

**Comment by hotalex** [comment]
The problem has been solved, thank you very much!

**Comment by hotalex** [comment]
I don't know where to set off this problem!

**Comment by Nick088Official** [comment]
You're welcome!
