### ISSUE TITLE
some upgrades

### ISSUE THREAD

**Issue by addy005** [Nick088Official/FaceFusion-Online-Ports#11]
Hello,
I used the GUI version of FaceFusion, and my two accounts got banned. Is there any way you can integrate Telegram with it? Using a bot token and chat ID, when the user runs the bot, it should ask for the source image and target video/picture. Then, it should provide some options or buttons where the user can select options like face enhancer, thread quality, etc. The bot should also update the user in Telegram about the process and send the final video or picture directly to Telegram.
and im not sure non gui banning or not i dont have any account right now

**Comment by Nick088Official** [comment]
Yea as its written on the Github Repository there's a Ban Risk Chance for using it as colab doesn't allow making deepfakes in general. Sorry to tell you but neither i use telegram nor i know how to code a telegram bot, also i don't have a pc or a free way to host it, considerating the much power consume that FaceFusion takes.

**Comment by Nick088Official** [comment]
You could try the new [lightning.ai port](https://lightning.ai/nick088/studios/facefusion-ui), which has no disallowed code isssue, but I can't make a telegram bot
