### ISSUE TITLE
Runtime Disconnecting Issue

### ISSUE THREAD

**Issue by maheshbhanushali** [Nick088Official/FaceFusion-Online-Ports#14]
Your runtime has been disconnected due to executing code that is disallowed in our free-of-charge tier. Colab subsidises millions of users and prioritises interactive programming sessions while disallowing some types of usage as outlined in the [FAQs](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions). If you believe this message is in error, [file an appeal]

**Comment by maheshbhanushali** [comment]
> I just encrypted it again even more the code now, Refresh the colab and retry, tell me if the error still persists, as on my end it worked fine

Same problem again, works for at least 5 minutes and then same error.

**Comment by maheshbhanushali** [comment]
It works fine during normal use, but I get an error whenever I try to use the face enhancer mode.

**Comment by awesome24e** [comment]
If I wanted to open one of the hidden .py files, how would I do so? Currently, when attempting to do so, an error "Could not fetch [file name] from backend" occurs.

**Comment by Nick088Official** [comment]
> If I wanted to open one of the hidden .py files, how would I do so? Currently, when attempting to do so, an error "Could not fetch [file name] from backend" occurs.

Btw, next time make your own issue as this is a different thing.
Yea i made the files hidden in case it would help with not being detected, however colab doesn't let you open hidden files, so you would need to unhide them, that could be risky. Also, why would you need to open the .py files? In the Colab notebooks you don't to open any files

**Comment by gilroff** [comment]
> > If I wanted to open one of the hidden .py files, how would I do so? Currently, when attempting to do so, an error "Could not fetch [file name] from backend" occurs.
> 
> Btw, next time make your own issue as this is a different thing. Yea as of right now i made the files hidden in case it would help with not being detected, however colab doesn't let you open hidden files, so you would need to unhide them, that could be risky. Also, why would you need to open the .py files? In the Colab notebooks you don't need to open any .py files

To turn off the nsfw filter. There's no other way to turn it off. Can you provide a button or code block to turn it off?

**Comment by gilroff** [comment]
Btw I'm still getting disconnected after 30 mins.

**Comment by Nick088Official** [comment]
> > > If I wanted to open one of the hidden .py files, how would I do so? Currently, when attempting to do so, an error "Could not fetch [file name] from backend" occurs.
> > 
> > 
> > Btw, next time make your own issue as this is a different thing. Yea as of right now i made the files hidden in case it would help with not being detected, however colab doesn't let you open hidden files, so you would need to unhide them, that could be risky. Also, why would you need to open the .py files? In the Colab notebooks you don't need to open any .py files
> 
> To turn off the nsfw filter. There's no other way to turn it off. Can you add a checkbox or code block to turn it off?

FaceFusion doesn't allow NSFW, I'm not gonna help for that.
