### ISSUE TITLE
Headless no UI Uploading and Executing error

### ISSUE THREAD

**Issue by Katsukipp** [Nick088Official/FaceFusion-Online-Ports#16]
**this happen when i mount the google drive :**

Mounted at /content/drive
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-2-1c435dab3969>](https://localhost:8080/#) in <cell line: 13>()
     11 # Define the parent directory path
     12 FF_GD_name_enc = "==gZmJXex5mcV9VYiZnZoNlcw52U"
---> 13 FF_GD_name = dec(FF_GF_name_enc)
     14 parent_dir = f'/content/drive/MyDrive/{FF_GD_name}'
     15 

NameError: name 'dec' is not defined

**and this happen when i force to execute the program**

/content
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-3d8c24eafa8b> in <cell line: 25>()
     23 
     24 program_name_enc = "==QYiZnZoNncw52c"
---> 25 program_name = dec(program_name_enc)
     26 
     27 if git_branch == "master":

NameError: name 'dec' is not defined

**Comment by Nick088Official** [comment]
Thank you for reporting it, just fixed it!

**Comment by Katsukipp** [comment]
> Thank you for reporting it, just fixed it!

its still got this error when i run the mount googledrive cell

`Mounted at /content/drive
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-2-d2b1919902ad>](https://localhost:8080/#) in <cell line: 13>()
     11 # Define the parent directory path
     12 FF_GD_name_enc = "==gZmJXex5mcV9VYiZnZoNlcw52U"
---> 13 FF_GD_name = _N_Vy9m_(FF_GF_name_enc)
     14 parent_dir = f'/content/drive/MyDrive/{FF_GD_name}'
     15 

NameError: name 'FF_GF_name_enc' is not defined`

**Comment by Nick088Official** [comment]
Oops, I did a typo, fixed it just right now

**Comment by Katsukipp** [comment]
> Oops, I did a typo, fixed it just right now

now i got this 😭 



Mounted at /content/drive
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-1-cb15c6c60ce4>](https://localhost:8080/#) in <cell line: 13>()
     11 # Define the parent directory path
     12 FF_GD_name_enc = "==gZmJXex5mcV9VYiZnZoNlcw52U"
---> 13 FF_GD_name = _N_Vy9m_(FF_GD_name_enc)
     14 parent_dir = f'/content/drive/MyDrive/{FF_GD_name}'
     15 

NameError: name '_N_Vy9m_' is not defined

**Comment by Nick088Official** [comment]
Did you restart the runtime after running the install cell? Did you get a popup asking to restart the runtime while running the install cell on a branch?
