### ISSUE TITLE
Run UI is impossible

### ISSUE THREAD

**Issue by Dragneure** [Nick088Official/FaceFusion-Online-Ports#19]
The run cell doesn't start,

NameError                                 Traceback (most recent call last)
[<ipython-input-9-8332b4eb140c>](https://localhost:8080/#) in <cell line: 30>()
     28 Target = "" #@param {type:"string"}
     29 
---> 30 Source_Image = f"/content/drive/MyDrive/{FF_GD_name}/Inputs/{Source_Image}"
     31 Target = f"/content/drive/MyDrive/{FF_GD_name}/Inputs/{Target}"
     32 

NameError: name 'FF_GD_name' is not defined

**Comment by Dragneure** [comment]
I didn't run the drive cell, i'm an android user and i didn't mount drive neither

**Comment by Dragneure** [comment]
I guess that the last cell is missing a split, bc It should be possible run it without drive inputs, right?

**Comment by Dragneure** [comment]
I don't catch how works the drive cells

**Comment by Dragneure** [comment]
And if i can run it without run those cells

**Comment by zin-header** [comment]
still detected by collab, and Gcollab forcibly disconnected the tunnel

**Comment by Nick088Official** [comment]
> I guess that the last cell is missing a split, bc It should be possible to run it without drive inputs, right?

Yes

> I don't catch how works the drive cells

Btw, Its written in the guide inside of the colab at the top

> The run cell doesn't start,
> 
> NameError Traceback (most recent call last) in <cell line: 30>() 28 Target = "" #@param {type:"string"} 29 ---> 30 Source_Image = f"/content/drive/MyDrive/{FF_GD_name}/Inputs/{Source_Image}" 31 Target = f"/content/drive/MyDrive/{FF_GD_name}/Inputs/{Target}" 32
> 
> NameError: name 'FF_GD_name' is not defined

This has just got fixed!

**Comment by Nick088Official** [comment]
> still detected by collab, and Gcollab forcibly disconnected the tunnel

How long did it last? and also say which tunnel. Google Colab Detection is very random so for some accounts it could happen for some others not

**Comment by zin-header** [comment]
> > still detected by collab, and Gcollab forcibly disconnected the tunnel
> 
> How long did it last? and also say which tunnel. Google Colab Detection is very random so for some accounts it could happen for some others not

gradio, after above 5 minutes

**Comment by Nick088Official** [comment]
> > > still detected by collab, and Gcollab forcibly disconnected the tunnel
> > 
> > 
> > How long did it last? and also say which tunnel. Google Colab Detection is very random so for some accounts it could happen for some others not
> 
> gradio, after above 5 minutes

Try with maybe alt accounts, and be sure to be using my latest version, i will leave this closed tho as its a different issue of a different user
