### ISSUE TITLE
Facefusion Last not work...give me this Error....

### ISSUE THREAD

**Issue by MumbaiShiva** [Nick088Official/FaceFusion-Online-Ports#20]
Dear Friends, 
After some time, I am using the Facefusion program again, but I found that it does not work in the latest repository published by you. I install regularly, but when I start the RUN but without using Google Drive and using Gradio, it gives me this error

Error: Traceback (most recent call last):
  File "/content/.program/run.py", line 7, in <module>
    from PROGRAM import core
  File "/content/.program/PROGRAM/core.py", line 8, in <module>
    from PROGRAM import content_analyser, face_classifier, face_detector, face_landmarker, face_masker, face_recognizer, logger, process_manager, state_manager, voice_extractor, wording
  File "/content/.program/PROGRAM/content_analyser.py", line 9, in <module>
    import PROGRAM.globals
ModuleNotFoundError: No module named 'PROGRAM.globals'

what i did wrong? what i have to use? Can you solve it?
Thanks a lot for your reply.

**Comment by Nick088Official** [comment]
Did you change anything inside the files? Like manually change the .py files

**Comment by Nick088Official** [comment]
I just tried running the ui colab myself both on cpu and gpu without google drive using gradio, with no issues.
If you tried to change the files to remove the NSFW Filter, I’m not gonna help for that as said in the [FAQ](https://github.com/Nick088Official/FaceFusion-Online-Ports?tab=readme-ov-file#are-you-going-to-help-to-remove-the-nsfw-filter-or-make-a-way-to-use-facefusion-without-filter)
