### ISSUE TITLE
CV2 Error / Error at analysing step 51% 

### ISSUE THREAD

**Issue by MuzahidGithub** [Nick088Official/FaceFusion-Online-Ports#22]
got this error : cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by Nick088Official** [comment]
Did you modify anything of the py files / Try to remove the NSFW Filter?

**Comment by Nick088Official** [comment]
Else it could be a Metadata problem with your target/source file, which fix could be saving the source image file as a jpg and reconverting the video to mp4

**Comment by MuzahidGithub** [comment]
No modifications made. Just copied to drive and run

**Comment by Nick088Official** [comment]
> No modifications made. Just copied to drive and run

Alright, then it could be a metadata problem inside either the target or source file. For the source file, its better to export it as jpg, while for the target, if its a video re-export it as mp4, if its an image re export it to jpg

**Comment by Nick088Official** [comment]
Will close this as there’s no reply.
