### ISSUE TITLE
Paperspace notebook (not an issue)

### ISSUE THREAD

**Issue by gilroff** [Nick088Official/FaceFusion-Online-Ports#24]
Can you please keep the google drive as only an option and not the default for the future?
It will save us paperspace users some headache trying to make it work.

**Comment by Nick088Official** [comment]
Yea, I won't make google drive mandatory as not everyone wants to mount drive anyways

Also, if you made a paperspace version and want to share it, you could send it here and I could link it from this issue to the README
Or if you dont want to I can just close this issue

**Comment by gilroff** [comment]
@Nick088Official Yes I have no problem with that. But how should I proceed. Should I make a new github with just the edited notebook?
Also the latest version is kinda buggy. error pop up messages come up every now and then even though it doesnt crash.
Let me check in detail if everything works smoothly and I will notify you here

**Comment by gilroff** [comment]
@Nick088Official Okay, I have made a new repository and the notebook seems to be running without much issues:
[https://github.com/gilroff/Facefusion-Paperspace](https://github.com/gilroff/Facefusion-Paperspace)

**Comment by Nick088Official** [comment]
> @Nick088Official Okay, I have made a new repository and the notebook seems to be running without much issues: https://github.com/gilroff/Facefusion-Paperspace

Alright, added it. It will stay in this repository as long as the notebook won't ever remove the nsfw filter as the program is gainst that

**Comment by gilroff** [comment]
> > @Nick088Official Okay, I have made a new repository and the notebook seems to be running without much issues: https://github.com/gilroff/Facefusion-Paperspace
> 
> Alright, added it. It will stay in this repository as long as the notebook won't ever remove the nsfw filter as the program is gainst that

No worries about that. Btw, will it be too much work for you to make a simpler notebook in the next update without all the encryption stuff meant for colab? It will make the paperspace notebook much more readable and clean.

**Comment by Nick088Official** [comment]
> > > @Nick088Official Okay, I have made a new repository and the notebook seems to be running without much issues: https://github.com/gilroff/Facefusion-Paperspace
> > 
> > Alright, added it. It will stay in this repository as long as the notebook won't ever remove the nsfw filter as the program is gainst that
> 
> No worries about that. Btw, will it be too much work for you to make a separate simpler notebook in the next update without all the encryption stuff meant for colab? It will make the paperspace notebook much more readable and clean.

I can't remove the encryption from the Google Colabs as it will make them just even more detectable, but you could see the code if the lightning.ai notebooks which isn't encrypted and pretty similar
