### ISSUE TITLE
Lightning AI no longer works

### ISSUE THREAD

**Issue by xd003** [Nick088Official/FaceFusion-Online-Ports#27]
After we click on the `Open in Studio` button, it says "This Studio cannot be opened. Please, [contact support](mailto:support@lightning.ai)"

![image](https://github.com/user-attachments/assets/b9559046-e458-4923-b7c2-1dcfbe9ef113)

**Comment by Nick088Official** [comment]
> After we click on the `Open in Studio` button, it says "This Studio cannot be opened. Please, [contact support](mailto:support@lightning.ai)"
> 
> ![image](https://private-user-images.githubusercontent.com/26503185/376444064-b9559046-e458-4923-b7c2-1dcfbe9ef113.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODEwNjIsIm5iZiI6MTcyODk4MDc2MiwicGF0aCI6Ii8yNjUwMzE4NS8zNzY0NDQwNjQtYjk1NTkwNDYtZTQ1OC00OTIzLWI3YzItMWRjZmJlOWVmMTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4MjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOWZlMTlkZjgxYzY5NWQwMjUzYjdhMzFhNTc4NTE1MzJkZWYxOTQ4OThkNzZkYWVjNTM0MGU3NzE3NzY0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pFNrb5XeuDdxgJf_Ocl1FkY_LleJazkzQP2wqaLWaR0)

Hey, I just tried myself and I was able to open it in studio and also other studio templates worked, could u see if u can open in studio other templates in https://lightning.ai/studios ? I might think this is an issue related to your account, it would be better you contact their support via their email (via the hyperlink, the blue text “contact support”) or via their discord server https://discord.com/invite/MWAEvnC5fU. Unfortunately I can’t help with issues related to your account, but a lightning.ai staff can.

**Comment by xd003** [comment]
I can confirm that it's a account related restriction. I will take it up on their discord. Thanks for the heads up

**Comment by xd003** [comment]
Hello @Nick088Official Can you please fix your discord invite link in github, it says its invalid
