### ISSUE TITLE
Today your repository FaceFusion_UI.ipynb not work with Gradio

### ISSUE THREAD

**Issue by MumbaiShiva** [Nick088Official/FaceFusion-Online-Ports#3]
Hello from India, 
sorry for disturb you but today when i'am using your Repository: FaceFusion_UI.ipynb, it not work it give me this error:

/content/3dyrb6e7
Downloading: 100% 22.5M/22.5M [00:00<00:00, 43.0MB/s]
Downloading: 100% 93.4M/93.4M [00:00<00:00, 102MB/s]
Downloading: 100% 922k/922k [00:00<00:00, 1.95MB/s] 
Downloading: 100% 1.26M/1.26M [00:00<00:00, 2.84MB/s]
Downloading: 100% 12.1M/12.1M [00:00<00:00, 24.6MB/s]
Downloading: 100% 166M/166M [00:01<00:00, 119MB/s]
Downloading: 100% 67.1M/67.1M [00:00<00:00, 73.1MB/s]
Downloading: 100% 50.7M/50.7M [00:01<00:00, 52.7MB/s]
Downloading: 100% 63.7M/63.7M [00:00<00:00, 67.1MB/s]
Downloading: 100% 265M/265M [00:02<00:00, 98.1MB/s]
Running on local URL:  http://127.0.0.1:7860

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio

 can you explain me why?
Thank you for help.

**Comment by Nick088Official** [comment]
Gradio (Python package for the UI) is having problems today, its API for the public link is going up and down, you can check their status here https://status.gradio.app/. Also i added an Ngrok Option for the UI Colab. Or if you want you can try the UI Kaggle (that uses Ngrok too)

**Comment by Nick088Official** [comment]
Btw i also added other tunnel options as gradio share api is having a lot of problems recently, i will close this issie
