### ISSUE TITLE
Today your repository not working good Repository: FaceFusion_UI.ipynb

### ISSUE THREAD

**Issue by MumbaiShiva** [Nick088Official/FaceFusion-Online-Ports#5]
Hello Friend, I need your help.
When i play yuour Repository and try start first Line "Install" it after some seconds tell me Installed but it not installed, and not work.
What is happened? Until this morning all worked good. Now look like when i open repository and run it on the left not all FaceFusion Elements installed....
i Will wait for solutions. Thank you

**Comment by Nick088Official** [comment]
Just looked into that and fixed it, it was having problems to git clone facefusion because of tinyurl human verification, so i used rot 13 encryption to bypass so that facefusion still doesn't get detected, please let me know if you got other issues
