### ISSUE TITLE
Need a Version for PaperSpace Gradient

### ISSUE THREAD

**Issue by xenstar** [Nick088Official/FaceFusion-Online-Ports#8]
Hi Bro, I was trying to setup your Jupiter Notebook on PaperSpace but noticed that you are using ngrock and Cloudflare tunnel which is against Paperspace TOS. Can you make a version with gradio only, then I can easily import it to Jupiter notebook on paper space. would be very helpful..

**Comment by Nick088Official** [comment]
Hello, I don't think i will ever make a paperspace port as the free gpu is almost always at capacity lol, and about tunneling, i searched up and i might think even gradio web ui could get detected as its still a tunnel and it seems like they don't allow any of those. Anyways idk much of paperspace gradient, but in my web ui google colab there's also the code for using only the gradio one, you would just need to remove the other pieces of the code about the other tunnels and use only gradio

**Comment by xenstar** [comment]
Actually if you choose the Pro Plan, then every few minutes after refreshing they will give you free gpu. So I was using smoothly yesterday the roop unleashed, wanted to try face fusion, but none of the collab worked.

" you would just need to remove the other pieces of the code about the other tunnels and use only gradio"

Can you tell me which line? I couldn't find that option.

**Comment by Nick088Official** [comment]
The paperspace pro plan isn't free, so its not really 'free gpus' but just gpu integrated in your paid plan lol. Btw roop unleashed is a fork of the older version of facefusion named roop, which ofc has lower quality. Anyways, i dont know much how paperspace works, but if you can upload the ipynb notebook file, then you'd just need to remove the Tunnel Variable, all the markdowns about ngrok and tunnels, every 'elif Tunnel ==...' and just leave the gradio code one which is: 
`  file_path_ui_rot13 = "/pbagrag/snprshfvba/snprshfvba/hvf/ynlbhgf/qrsnhyg.cl"
  file_path_ui = codecs.decode(file_path_ui_rot13, 'rot 13')
  !sed -i 's/quiet = True/quiet=True,share=True/g' $file_path_ui`

**Comment by xenstar** [comment]
if you are online, i can give you access to my server, so you can play with it

**Comment by xenstar** [comment]
I subscribed for 8$, so wanted to utilize it.

I could run the first part of the code successfully
![image](https://github.com/Nick088Official/FaceFusion-Online-Ports/assets/55502651/109d8efd-c18f-4c8f-bf8c-70422d74f50a)


. But in jupyter notebook, when i try to run this, it just open new section, but doesn't run the code. Can you help to keep only the gradio part. Sorry I am not very good with python coding. 


"import os

import codecs

import re

 

# Change directory

os.chdir(f"/notebooks/{directory}")

 

#@markdown The type of tunnel you wanna use for seeing the public link, so if the API of one of them is down, you can use the other one.

Tunnel = "LocalTunnel" #@param ["Gradio", "Ngrok", "Cloudfare", "LocalTunnel"]

 

#@markdown Also when using Ngrok, Cloudfare or LocalTunnel as the Tunnel, you need to wait for the Local URL to appear, and only after that click on the Public URL above it.

 

#@markdown Use the option under this only if you chose Ngrok as the Tunnel:

 

#@markdown You can get the Ngrok Tunnel Authtoken here: https://dashboard.ngrok.com/tunnels/authtokens/new.

 

ngrok_tunnel_authtoken = "" #@param {type:"string"}

 

if Tunnel == "Gradio":

file_path_ui_rot13 = "/pbagrag/snprshfvba/snprshfvba/hvf/ynlbhgf/qrsnhyg.cl"

file_path_ui = codecs.decode(file_path_ui_rot13, 'rot 13')

!sed -i 's/quiet = True/quiet=True,share=True/g' $file_path_ui

elif Tunnel == "Ngrok":

!sed -i 's/quiet=True,share=True/quiet = True/g' $file_path_ui

!pip install pyngrok

from pyngrok import ngrok

ngrok.set_auth_token(ngrok_tunnel_authtoken)

http_tunnel = ngrok.connect(7860, bind_tls=True)

from IPython.display import clear_output

clear_output()

print("Ngrok Tunnel Public URL:", http_tunnel.public_url)

elif Tunnel == "Cloudfare":

!sed -i 's/quiet=True,share=True/quiet = True/g' $file_path_ui

# download cloudfare

!curl -LO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb

!dpkg -i cloudflared-linux-amd64.deb

!rm -rf nohup.out

import time

# Run cloudflare

!nohup cloudflared tunnel --url localhost:7860 &

from IPython.display import clear_output

clear_output()

time.sleep(5)

# Find and print the Cloudflare URL with a prefix

cloudflare_url = !grep -oE "https://[a-zA-Z0-9.-]+\.trycloudflare\.com" nohup.out

print(f"Cloudfare Tunnel Public URL: {cloudflare_url[0]}")

elif Tunnel == "LocalTunnel":

!sed -i 's/quiet=True,share=True/quiet = True/g' $file_path_ui

# install

!npm install -g localtunnel

import time

import urllib

# run localtunnel

with open('url.txt', 'w') as file:

file.write('')

 

get_ipython().system_raw('lt --port 7860 >> url.txt 2>&1 &')

 

time.sleep(4)

 

endpoint_ip = urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n")

 

with open('url.txt', 'r') as file:

tunnel_url = file.read()

tunnel_url = tunnel_url.replace("your url is: ", "")

 

from IPython.display import clear_output

clear_output()

print(f"LocalTunnel Tunnel Public URL: \033[0m\033[93m{tunnel_url}\033[0m", end="\033[0m")

 

print(f'LocalTunnel Password: {endpoint_ip}')

 

 

if device == "cuda":

!python run.py --execution-providers cuda

else:

!python run.py --execution-providers cpu"

**Comment by Nick088Official** [comment]
Was sleeping lol, im back, the code keeping only the gradio tunnel would look like:
`
#@title Run UI

import codecs
import re

%cd /content/$directory

file_path_ui_rot13 = "/pbagrag/snprshfvba/snprshfvba/hvf/ynlbhgf/qrsnhyg.cl"
file_path_ui = codecs.decode(file_path_ui_rot13, 'rot 13')
!sed -i 's/quiet = True/quiet=True,share=True/g' $file_path_ui

if device=="cuda":
  !python run.py --execution-providers cuda
else:
  !python run.py --execution-providers cpu
`
As you probably noticed, it has some encryptions so that there's less chances for the web ui to get detected, as it might get you banned if as you said paperspace bans web uis. 'file_path_ui' is '/content/facefusion/facefusion/uis/layouts/default.py' you might have to change the 'content' part to whatever is the main directory for paperspace, so like the folder where facefusion gets downloaded, which from what i seen online is either 'storage' or 'notebooks'. This way it should be able to run correctly

**Comment by xenstar** [comment]
Ohh understand. I can see a lot of free gpus available after i subscribe to pro version. If you are online let me know, telegram - xenstar, i will give you access and you can try. 

Paperspace also can expose directly with https://tensorboard-xxxxx.paperspacegradient.com This type of link aswell, no need for tunneling, but i don't know how...  -_-

**Comment by Nick088Official** [comment]
Sorry but i don't use telegram, and honestly i don't know what's that paperspace type of tunnel and can't seem to find anything online about it but from the name i think it's only for the tensorboard, soo idk if it would work to see the facefusion ii

**Comment by gilroff** [comment]
Hey, I would love to have a paperspace notebook too. Free colab stops in the middle of processing saying its disallowed code. So, if i'm paying for it, paperspace is much better. it has faster cpus and gpus. Can you please port it? I dont know how to code at all. 
About the paperspace tunnel, its just like local tunnel from what I've seen.

**Comment by xenstar** [comment]
> Hey, I would love to have a paperspace notebook too. Free colab stops in the middle of processing saying its disallowed code. So, if i'm paying for it, paperspace is much better. it has faster cpus and gpus. Can you please port it? I dont know how to code at all. About the paperspace tunnel, it works just like local tunnel from what I've seen.

It is much more faster and smoother than collab free and kaggle. If I get a cpu for 6 hour, can do a lot. currently I am using roop unleashed as i can successfully run it there. But I still cannot run facefusion, and nobody helped me :'( I wasted 2 days trying, but i am not a coder, so it's hard.

**Comment by gilroff** [comment]
> > Hey, I would love to have a paperspace notebook too. Free colab stops in the middle of processing saying its disallowed code. So, if i'm paying for it, paperspace is much better. it has faster cpus and gpus. Can you please port it? I dont know how to code at all. About the paperspace tunnel, it works just like local tunnel from what I've seen.
> 
> It is much more faster and smoother than collab free and kaggle. If I get a cpu for 6 hour, can do a lot. currently I am using roop unleashed as i can successfully run it there. But I still cannot run facefusion, and nobody helped me :'( I wasted 2 days trying, but i am not a coder, so it's hard.

Its faster and cheaper than paid colab too.

**Comment by xenstar** [comment]
> Its faster and cheaper than paid colab too.

Yeah, we can't tell people about it, then it will be more harder to get Free GPUS in pro plan. 🤣 I hope Nick will make a version for FaceFusion too in paperspace.

**Comment by gilroff** [comment]
hahaa. yeah keeping my fingers crossed.

**Comment by gilroff** [comment]
@xenstar @Nick088Official 
I found a hack to make it run in gradient paper space.
Select local tunnel in the colab notebook and copy the code (I think this is the least risky option).
Then, add this right after "ngrok_tunnel_authtoken = "" #@param {type:"string"}" in the second code part:

import os

file_path = os.path.join("/users", "1002")

**Comment by xenstar** [comment]
I stopped using on paperspace. Now using Novita.ai, they have pre built face fusion. It just cost 0.35$ per hour for rtx 4090 24GB GPU. Super fast.

**Comment by gilroff** [comment]
> I stopped using on paperspace. Now using Novita.ai, they have pre built face fusion. It just cost 0.35$ per hour for rtx 4090 24GB GPU. Super fast.

oh cool

**Comment by gilroff** [comment]
@Nick088Official 
I think the last update you did fixed an issue in paperspace. When the video was processing, the progress was not shown in the output in the notebook yesterday. But after the last update, its displaying, but still its cut off in the middle of execution provider text. don't know why.

**Comment by Nick088Official** [comment]
> @xenstar @Nick088Official I found a hack to make it run in gradient paper space. Filesystem doesn't show up as in colab, but the web UI works. Select local tunnel in the colab notebook and copy the code (I think local tunnel is the least risky option). Then, add this right after "ngrok_tunnel_authtoken = "" #@param {type:"string"}" in the second code part:
> 
> import os
> 
> file_path = os.path.join("/users", "1002")

From what I know, paperspace allow Web UIs so there is nothing to worry about the tunnels. I don't really understand the file_path part as I never used PaperSpace, but atleast seems like it works.



> @Nick088Official I think the last update you did fixed an issue in paperspace. When the video was processing, the progress was not shown in the output in the notebook yesterday. But after the last update, its displaying, but still its cut off in the middle of execution provider text. don't know why.

Kinda weird, on colab i don't run in those issues on the latest commit.

**Comment by thegamblers** [comment]
I'm facing runtime disconnected issues with colab, whenever i run the UI version of Facefusion and only after the 2nd generation, whenever i try to generate the 3rd video, it automatically disconnects the runtime.

**Comment by Nick088Official** [comment]
> I'm facing runtime disconnected issues with colab, whenever i run the UI version of Facefusion and only after the 2nd generation, whenever i try to generate the 3rd video, it automatically disconnects the runtime.

This is an issue about PaperSpace (which in fact I will close Now as I'm not going to make a PaperSpace version as I don't pay for it. Also it's better to make an own issue about this, and also I will look into it (my current suggestion is to try with different accounts and split the video to 1 min)
